export enum AuditAction {
  AUTH_VERIFY_SUCCESS     = 'AUTH_VERIFY_SUCCESS',
  AUTH_VERIFY_FAILURE     = 'AUTH_VERIFY_FAILURE',
  AUTH_VERIFY_LOCKED      = 'AUTH_VERIFY_LOCKED',
  AUTH_VERIFY_REJECTED    = 'AUTH_VERIFY_REJECTED',
  AUTH_USER_PROVISIONED   = 'AUTH_USER_PROVISIONED',
  AUTH_UID_MISMATCH       = 'AUTH_UID_MISMATCH',
  AUTH_TOKEN_INVALID      = 'AUTH_TOKEN_INVALID',
  TENANT_CLAIM_CONFLICT   = 'TENANT_CLAIM_CONFLICT',
  TENANT_BOOT             = 'TENANT_BOOT',
}
