import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tableRegistry } from '../schema/_helpers/registry';

export function generateRlsSql(): string {
  const parts: string[] = ['-- AUTO-GENERATED by generate-rls.ts. Do not edit by hand.\n'];
  for (const meta of tableRegistry.list()) {
    if (meta.kind !== 'tenant') continue;
    parts.push(`-- ${meta.name}`);
    parts.push(`ALTER TABLE ${meta.name} ENABLE ROW LEVEL SECURITY;`);
    parts.push(`ALTER TABLE ${meta.name} FORCE ROW LEVEL SECURITY;`);
    parts.push(`DROP POLICY IF EXISTS rls_${meta.name}_tenant_isolation ON ${meta.name};`);
    parts.push(
      `CREATE POLICY rls_${meta.name}_tenant_isolation ON ${meta.name}\n` +
      `  FOR ALL\n` +
      `  USING (shop_id = current_setting('app.current_shop_id', true)::uuid)\n` +
      `  WITH CHECK (shop_id = current_setting('app.current_shop_id', true)::uuid);`,
    );
    parts.push('');
  }
  return parts.join('\n');
}

// CLI entry point — invoked via `tsx src/codegen/generate-rls.ts`
// Uses the same Windows-safe argv[1] check pattern as assert-all-tables-marked.ts.
const invoked = process.argv[1] ?? '';
if (invoked.endsWith('generate-rls.ts') || invoked.endsWith('generate-rls.js')) {
  // Dynamic side-effect import so the pure function above stays clean for tests.
  import('../schema')
    .then(() => {
      const out = generateRlsSql();
      const target = join(process.cwd(), 'packages/db/src/migrations/__generated__rls.sql');
      writeFileSync(target, out);
      console.log(`wrote ${target}`);
    })
    .catch((err) => {
      console.error('generate-rls: failed to load schema', err);
      process.exit(1);
    });
}
